name: Java CI

# This workflow triggers on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest  # Specifies the environment to use

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the Java version you are using

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # Step 4: Run tests with Maven
      - name: Run tests
        run: mvn test
