name: Run Test on Every Push
on:
  push:
    branches:
      - master
      - staging

  pull_request:
    branches:
      - master
      - staging

jobs:

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: master
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies & Test
      run: npm install && npm run test
