name: Run Test on Every Push
on:
  push:
    branches:
      - master
      - staging

  pull_request:
    branches:
      - master
      - staging

jobs:

  frontend-test:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v3

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Run Tests
      run: npm run test 
